// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DMS.Migrations
{
    [DbContext(typeof(DmsDbContext))]
    [Migration("20260315120330_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.4");

            modelBuilder.Entity("PrivateMessage", b =>
                {
                    b.Property<int>("MessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ReceiverUUID")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SenderUUID")
                        .HasColumnType("TEXT");

                    b.HasKey("MessageId");

                    b.ToTable("Wiadomości_Prywatne", null, t =>
                        {
                            t.HasCheckConstraint("CK_Message_NotEmpty", "trim(Content) <> ''");
                        });
                });

            modelBuilder.Entity("User", b =>
                {
                    b.Property<Guid>("UUID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("UUID");

                    b.ToTable("Użytkownicy", (string)null);
                });

            modelBuilder.Entity("UserInfo", b =>
                {
                    b.Property<Guid>("UUID")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayMode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Region")
                        .HasColumnType("TEXT");

                    b.HasKey("UUID");

                    b.ToTable("Info_Użytkownicy", (string)null);
                });

            modelBuilder.Entity("UserInfo", b =>
                {
                    b.HasOne("User", "User")
                        .WithOne("Info")
                        .HasForeignKey("UserInfo", "UUID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("User", b =>
                {
                    b.Navigation("Info")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
